### ISSUE TITLE
'SEGBatchIntegrationFactory.h' file not found

### ISSUE THREAD

**Issue by sirdharma** [BatchLabs/ios-segment-integration#3]
Hi,

I get the aforementioned compile error when trying to use `Segment-Batch/StaticLibWorkaround` with `use_frameworks!`. I know the documentation says to drag & drop the classes onto my project, but that can't be a solution. `Batch` is the only Pod that's doesn't work in my case with `use_frameworks!`.

It would really be appreciated if you could fix that.

Thanks!

**Comment by abarisain** [comment]
Hi,
Thanks for the feedback.

I do have some questions:

> Batch is the only Pod that's doesn't work in my case with use_frameworks!

Do you mean `Batch` as in the main Batch pod, or this pod?

>I know the documentation says to drag & drop the classes onto my project, but that can't be a solution.

It was until quite recently, due to Cocoapods limitations, so the ball was in their court.  
Fortunately, similar segment integrations only removed the workaround quite recently: https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/26/commits/289c286677e664ef584a3f900dcd82ffe56d1785
We'll investigate removing the workaround.

More importantly, did you try adding the classes and did it error out?

**Comment by abarisain** [comment]
Should be fixed in the remove_cocoapods_workaround branch

**Comment by sirdharma** [comment]
@abarisain Thank you! 👍

**Comment by sirdharma** [comment]
@abarisain Fix confirmed in the `fix_wrong_thread` branch. Thank you!

**Comment by sirdharma** [comment]
@abarisain Any ETA on when you'll release the changes?

**Comment by abarisain** [comment]
Sorry, that went under the radar for some reason.

I added this back on my todo list, it should be done soon.

**Comment by sirdharma** [comment]
@abarisain Thanks!

**Comment by abarisain** [comment]
1.1.0 has been pushed to cocoapods, so I will be closing this issue. Thanks for your help
